pipeline {
    agent { label 'jenkins-agent' }

    environment {
        HARBOR_REGISTRY      = '192.168.56.12:30080'
        HARBOR_PROJECT       = 'cicd-apps'
        DOCKER_IMAGE_NAME    = 'backend-app'
        HARBOR_CREDENTIAL_ID = 'harbor-credential'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Gradle') {
            steps {
                container('gradle') {
                    dir('BE-test') {
                        sh 'chmod +x gradlew'
                        sh './gradlew build'
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                container('docker') {
                    script {
                        dir('BE-test') {
                            withCredentials([usernamePassword(
                                credentialsId: HARBOR_CREDENTIAL_ID,
                                usernameVariable: 'HARBOR_USER',
                                passwordVariable: 'HARBOR_PASS'
                            )]) {
                                def imageTag      = "${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
                                def fullImageName = "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${imageTag}"

                                sh "docker login -u ${HARBOR_USER} -p ${HARBOR_PASS} ${HARBOR_REGISTRY}"
                                sh "docker build -t ${fullImageName} ."
                                sh "docker push ${fullImageName}"
                            }
                        }
                    }
                }
            }
        }
    }
}
